{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-model",
    "version": "8.12.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "builder-model-8.12.0-rc01.jar",
          "url": "builder-model-8.12.0-rc01.jar",
          "size": 138180,
          "sha512": "f094110bb087a8090e31057476e0825b8cb676c84f292c884258fce22a4e398f66c3bc4e26eeedfb44812504026f1a096c8db803d9a07e3a67106c2f06dec572",
          "sha256": "07994fec504bfa1748e7021b9233dc50daf602caec6f07b777312fe78971a772",
          "sha1": "b0fdfc8dc22887ab1f109ceca8d788f12e60811c",
          "md5": "22a7ed45ae479e39c478bcd7eac0169c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-8.12.0-rc01.jar",
          "url": "builder-model-8.12.0-rc01.jar",
          "size": 138180,
          "sha512": "f094110bb087a8090e31057476e0825b8cb676c84f292c884258fce22a4e398f66c3bc4e26eeedfb44812504026f1a096c8db803d9a07e3a67106c2f06dec572",
          "sha256": "07994fec504bfa1748e7021b9233dc50daf602caec6f07b777312fe78971a772",
          "sha1": "b0fdfc8dc22887ab1f109ceca8d788f12e60811c",
          "md5": "22a7ed45ae479e39c478bcd7eac0169c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.12.0-rc01-javadoc.jar",
          "url": "builder-model-8.12.0-rc01-javadoc.jar",
          "size": 291422,
          "sha512": "e4563ddf7c916e7221b34775d77b06e92fc535feb5464180989886e7d29d675ab65bdf9ddc6180040e9fb62dad2ab3f39d30c6b869161f0a890ef09470c240ef",
          "sha256": "6ae1df551c602d766c67ee3305ae42ef59829018ca07341215a9e4fbb3861327",
          "sha1": "430acf0f7f3055d49d2f21779b09267738252231",
          "md5": "d4cffa57701d296290e921fdbbfab7e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.12.0-rc01-sources.jar",
          "url": "builder-model-8.12.0-rc01-sources.jar",
          "size": 157723,
          "sha512": "a2fbbeacba274bb9007b2fb43698b67dba7679e733225c7d58c090915ebc0b80463eceacd7be9f40bd099fc1329fe39737387e273ad6d4126e95a4af12a30813",
          "sha256": "0856f4b590f3132d0e61ec23b24070b2703f06c0df940bc814830517fe91c2a7",
          "sha1": "7ee496edf35cb307984a72dc0fbc3ca5feaf1894",
          "md5": "0cf0a57d583842fbcfe05be328f705c4"
        }
      ]
    }
  ]
}
