{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.12.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.12.0-rc01"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.12.0-rc01.jar",
          "url": "builder-8.12.0-rc01.jar",
          "size": 15798452,
          "sha512": "c05ada229544cf8711a7744c7876cb2237053cfb352b444bdf4fd60d628bb414ad488d61aa9779031c14e02bf44782b712ce5f00c4c5df6bd8e0cfeaea9650d6",
          "sha256": "ff1473ede31bfa14c028ccd42da67b2c1e40a6d3850d3e89221f5eb5081b1d3e",
          "sha1": "1f8d78554b13f83802ff704a1aac948828cb19a4",
          "md5": "a57c1a3cc061cee678127c386977f8b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.12.0-rc01"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.12.0-rc01.jar",
          "url": "builder-8.12.0-rc01.jar",
          "size": 15798452,
          "sha512": "c05ada229544cf8711a7744c7876cb2237053cfb352b444bdf4fd60d628bb414ad488d61aa9779031c14e02bf44782b712ce5f00c4c5df6bd8e0cfeaea9650d6",
          "sha256": "ff1473ede31bfa14c028ccd42da67b2c1e40a6d3850d3e89221f5eb5081b1d3e",
          "sha1": "1f8d78554b13f83802ff704a1aac948828cb19a4",
          "md5": "a57c1a3cc061cee678127c386977f8b4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.12.0-rc01-javadoc.jar",
          "url": "builder-8.12.0-rc01-javadoc.jar",
          "size": 341755,
          "sha512": "cf4422641c2cb79b53700a389157aed11ed8a544833b5eca1d3b6e288956cb33fb70f96d2ff6f44263f52081eb631a26c955a46e009caeca44ba058e52ef36b4",
          "sha256": "ca737ecdf9fa9951567ad621e87d648e40728a9bf44e09593e6bb55ca395ec62",
          "sha1": "bcd549abbadd4dc175121649502a2dc4e4ee62a0",
          "md5": "7cb752c6be91548323903043926596cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.12.0-rc01-sources.jar",
          "url": "builder-8.12.0-rc01-sources.jar",
          "size": 283760,
          "sha512": "c34c863f77d532f95eaa23c8ff700bdd6db0d58fe747ca7d9f36242a57106865b8a8ce9e78a9d40052b4477eb2a7c2579ceed943e564ec1d933a3b090527d985",
          "sha256": "0de5fd47f85f20078f22af9699111b53df6d8d6595cb767d483ad0639eae966f",
          "sha1": "ff80a08e89aa1919a7ce3667713c8470fe4f9506",
          "md5": "df5ad0c4e58fec2c096bf96e7c2953c9"
        }
      ]
    }
  ]
}
