{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vanniktech",
    "module": "gradle-maven-publish-plugin",
    "version": "0.34.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-maven-publish-plugin-0.34.0.jar",
          "url": "gradle-maven-publish-plugin-0.34.0.jar",
          "size": 182689,
          "sha512": "de3013ebcc1cf9020aa8da9f6dc7366905ce6d025896ab99731933b432ca4ab3b3c05e71f4808ef7687c2483ed773f6c13a0c754321fa3a67b89d33e6097d49f",
          "sha256": "1b304ae327d7034de19511f77ad227ba59d7358e8b51d18b09da7a253fec4c05",
          "sha1": "67c4438a4246c2e26b2a54e3191222c92dc00ac6",
          "md5": "bc04bae4fe488c4cbc3ac144892be4ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.vanniktech",
          "module": "central-portal",
          "version": {
            "requires": "0.34.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-maven-publish-plugin-0.34.0.jar",
          "url": "gradle-maven-publish-plugin-0.34.0.jar",
          "size": 182689,
          "sha512": "de3013ebcc1cf9020aa8da9f6dc7366905ce6d025896ab99731933b432ca4ab3b3c05e71f4808ef7687c2483ed773f6c13a0c754321fa3a67b89d33e6097d49f",
          "sha256": "1b304ae327d7034de19511f77ad227ba59d7358e8b51d18b09da7a253fec4c05",
          "sha1": "67c4438a4246c2e26b2a54e3191222c92dc00ac6",
          "md5": "bc04bae4fe488c4cbc3ac144892be4ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-maven-publish-plugin-0.34.0-sources.jar",
          "url": "gradle-maven-publish-plugin-0.34.0-sources.jar",
          "size": 22083,
          "sha512": "9ffc1c419ace5967075b4cf969348ad6484af81b45230822c726fc55198977f5166cece8dee1527b0d62075d914e6d739a59c01cd3a423a9b2bcba88fe29d036",
          "sha256": "04f55465bb934686ed9beb43dffbe25b54c50f29b8e8c47d72d818ae48aaed2f",
          "sha1": "1d0da61baa81df8eacf26de6d2353187e434758f",
          "md5": "aee667abcf2d8ba805dfc8f22eebf2c4"
        }
      ]
    }
  ]
}
