{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "8.12.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-8.12.0-rc01.jar",
          "url": "aaptcompiler-8.12.0-rc01.jar",
          "size": 496115,
          "sha512": "0e51543e0fca7982b0f6a1e74f82f93ffeb58196a455cb27d93af55dc6ad98501f909d7c34138a8d6b850e3a0e390f01dd1ed5c93b8a79528731cb10a9402e7d",
          "sha256": "a77e6ddcc534bcd7ff498df35a1d1054a5e696fa315beb0b6c43f885d6cdc9d0",
          "sha1": "edc618d64bfa4a483440eb168fa96e63cc39c3bc",
          "md5": "c8db19898fc58bf0f93b23d2f49a5324"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.12.0-rc01-13700139"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-8.12.0-rc01.jar",
          "url": "aaptcompiler-8.12.0-rc01.jar",
          "size": 496115,
          "sha512": "0e51543e0fca7982b0f6a1e74f82f93ffeb58196a455cb27d93af55dc6ad98501f909d7c34138a8d6b850e3a0e390f01dd1ed5c93b8a79528731cb10a9402e7d",
          "sha256": "a77e6ddcc534bcd7ff498df35a1d1054a5e696fa315beb0b6c43f885d6cdc9d0",
          "sha1": "edc618d64bfa4a483440eb168fa96e63cc39c3bc",
          "md5": "c8db19898fc58bf0f93b23d2f49a5324"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.12.0-rc01-javadoc.jar",
          "url": "aaptcompiler-8.12.0-rc01-javadoc.jar",
          "size": 81065,
          "sha512": "e011cd7a66158c9187d6ffec3b870a045e8ae90a3ec910fb71a76fd08ee5087ad5fbaa22280adcc5dd2200873941ce7ff64b0b12486fced5963e033846c4b6a7",
          "sha256": "2887a41413bb8d19e761ad23086d750ed8fb97d54f9dd44170cef92ded47e9d6",
          "sha1": "d5d538cafa1ed2a1b314403ebf8ab710f59b1af2",
          "md5": "48e5a43206ac976ddde83a30ac6762a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-8.12.0-rc01-sources.jar",
          "url": "aaptcompiler-8.12.0-rc01-sources.jar",
          "size": 152981,
          "sha512": "05cc6e4395597b692a0ee51e5ab7ab20cb4fab5b0d2e3f56c6332dbb1fb47fe14cd160d5c8749e198c3b86558509ad835c7499d53c11370d1f6cf4ddfff11171",
          "sha256": "c247ef43a909ad73555faec2a5d895b132ef421454ed9efffee38f52dd7174d6",
          "sha1": "b34277198401a5bf8cc0bddc42ec092ea8a412d0",
          "md5": "14da1d5f13cf46d41d5cbfa87dd26d45"
        }
      ]
    }
  ]
}
