package com.example.deviceinfotest

data class DeviceInfoModel(
    // Always accessible
    val time: Long,
    val storage: Long,
    val model: String,
    val board: String,
    val brand: String,
    val session: String,
    val densityDpi: Int,
    val timeZone: String,
    val batteryPct: Int?,
    val userAgent: String,
    val isRooted: Boolean,
    val androidId: String,
    val osVersion: String,
    val batteryLevel: Int?,
    val appVersion: String,
    val deviceType: String,
    val browserName: String,
    val isEmulator: Boolean,
    val packageName: String,
    val deviceTimezone: Int,
    val isCharging: Boolean?,
    val manufacturer: String,
    val runningApiLevel: Int,
    val targetSdkVersion: Int,
    val browserVersion: String,
    val deviceLanguage: String,
    val screenResolution: String,
    // With permissions, else default/empty
    val externalStorageBytes: Long,
    val fineLocationAllowed: Boolean,
    val coarseLocationAllowed: Boolean,
    val externalStorageAvailable: Boolean,
)