{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "31.12.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-31.12.0-rc01.jar",
          "url": "manifest-merger-31.12.0-rc01.jar",
          "size": 266204,
          "sha512": "6e65c2c56444ec4e8ab5d1d47fdd24adec8e8fc51d45461ab35dd9bf88a6588844ad008de9714d6987bc4149d3b0a6e992bc569956cdf918b78f1854315f6909",
          "sha256": "b1cf5fa48979d3f6afca95168c324de87ac570f3b2e8f039810f38aa5463aef7",
          "sha1": "c59340bb3ff3af616f5993ed98bcb99973a4c0ad",
          "md5": "6ca4894be6a30f13351abbf806f02d8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.12.0-rc01"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-31.12.0-rc01.jar",
          "url": "manifest-merger-31.12.0-rc01.jar",
          "size": 266204,
          "sha512": "6e65c2c56444ec4e8ab5d1d47fdd24adec8e8fc51d45461ab35dd9bf88a6588844ad008de9714d6987bc4149d3b0a6e992bc569956cdf918b78f1854315f6909",
          "sha256": "b1cf5fa48979d3f6afca95168c324de87ac570f3b2e8f039810f38aa5463aef7",
          "sha1": "c59340bb3ff3af616f5993ed98bcb99973a4c0ad",
          "md5": "6ca4894be6a30f13351abbf806f02d8d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.12.0-rc01-javadoc.jar",
          "url": "manifest-merger-31.12.0-rc01-javadoc.jar",
          "size": 275875,
          "sha512": "ae68a0e21092bfcee344ed53c08eaad4d795683c6db5e70d80ee927945faaafc59e014f7ea8e8169421de533888f5326973b78ae5943be8334016e4ec2d83b37",
          "sha256": "477e1fb2e874af05fbddcd4a883ecee206ce7cee3acf8bafc051f40d9414d116",
          "sha1": "bcaff34468353a384913f44c4331907937e92369",
          "md5": "7aefa4788b2e997ce197d7c794200917"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-31.12.0-rc01-sources.jar",
          "url": "manifest-merger-31.12.0-rc01-sources.jar",
          "size": 238897,
          "sha512": "74ec71f185fc6a3e10795d6b771ff44ebb0fc698396e6806c22ca1fcf2aee322da0b1304f930c2052e64678b626c07a6c5a231a2c681588f40d6573076a60b26",
          "sha256": "d398948dbd2e4b6e7ae361ee91e2fa829de2326404747e78f88ad284d1f560b4",
          "sha1": "c107ea1de6870c720c6e5b350126b912facc3e27",
          "md5": "d58c53411bd387e043b6b0b659412061"
        }
      ]
    }
  ]
}
