{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.12.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.12.0-rc01.jar",
          "url": "gradle-settings-api-8.12.0-rc01.jar",
          "size": 9953,
          "sha512": "ed1f7c4ddc3942d3a858ac51c1450a0115b9814f1b7baeea8c01b854f7ba063fa51335270b54f59a47abf3e80f794b62c8873efc7ecc9201018548949732a461",
          "sha256": "b7c9e9700c8a0ac1119b468d1a63ba8460b59ede07b408c87eafec289b7c9a0f",
          "sha1": "cbc13cac158b8d571a0d1cd6f394bf14ee771f19",
          "md5": "abe072cdc163fa98414b41a6923150de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.12.0-rc01.jar",
          "url": "gradle-settings-api-8.12.0-rc01.jar",
          "size": 9953,
          "sha512": "ed1f7c4ddc3942d3a858ac51c1450a0115b9814f1b7baeea8c01b854f7ba063fa51335270b54f59a47abf3e80f794b62c8873efc7ecc9201018548949732a461",
          "sha256": "b7c9e9700c8a0ac1119b468d1a63ba8460b59ede07b408c87eafec289b7c9a0f",
          "sha1": "cbc13cac158b8d571a0d1cd6f394bf14ee771f19",
          "md5": "abe072cdc163fa98414b41a6923150de"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.12.0-rc01-javadoc.jar",
          "url": "gradle-settings-api-8.12.0-rc01-javadoc.jar",
          "size": 261,
          "sha512": "243bbf5946a635d22f422e5ec1db2f85b0393da2238338721323788eb5a5b102567541b09bce706bc606c98181a105838a941435429c858eec1df40439da55b6",
          "sha256": "62ee185ca2e613121e79f168dedf5ea34f3d0b6a07f3759533b47539ca4d612a",
          "sha1": "05776e64f202ea1aa7bbc71fc68198dfd2ac8c8e",
          "md5": "5d7d7728214c73a9e2d3608503cd2595"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.12.0-rc01-sources.jar",
          "url": "gradle-settings-api-8.12.0-rc01-sources.jar",
          "size": 9470,
          "sha512": "a2826c9bb0c423672f88f5d601fc28cf6aa84c2d7105c3a7b2d6124884625b5273adc9f054a0ecc0ea94719e001cdcc316066e1121e2c1e983f7ab7ec92d6970",
          "sha256": "a04c21416528278b163840dd58c58c5241ff0de9e1ab87f579efa7bc8d9a030a",
          "sha1": "a83278f1aa7d9a3c5aa63267927449748c7ab91e",
          "md5": "2e2f29822114587c6e1711e9e16dcfba"
        }
      ]
    }
  ]
}
