{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vanniktech",
    "module": "central-portal",
    "version": "0.34.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "central-portal-0.34.0.jar",
          "url": "central-portal-0.34.0.jar",
          "size": 9218,
          "sha512": "1edca9ce460f40e787f4de3025cf94fb7f6dcec34001888a4cc40f6e30a83ae797a7cecff9619979c0f3b980f146505d6acd5f26dd769ffdae513c577eed335a",
          "sha256": "f47c96df5e76fae4351f8e8ef2a0054ed4cabef7f3373260c0f56fef263d2136",
          "sha1": "dcef9ef466623a0c16dbcbe5a24eb4db8ddbd977",
          "md5": "09c0bbd1f3abc863e35377cef835e1d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "central-portal-0.34.0.jar",
          "url": "central-portal-0.34.0.jar",
          "size": 9218,
          "sha512": "1edca9ce460f40e787f4de3025cf94fb7f6dcec34001888a4cc40f6e30a83ae797a7cecff9619979c0f3b980f146505d6acd5f26dd769ffdae513c577eed335a",
          "sha256": "f47c96df5e76fae4351f8e8ef2a0054ed4cabef7f3373260c0f56fef263d2136",
          "sha1": "dcef9ef466623a0c16dbcbe5a24eb4db8ddbd977",
          "md5": "09c0bbd1f3abc863e35377cef835e1d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "central-portal-0.34.0-sources.jar",
          "url": "central-portal-0.34.0-sources.jar",
          "size": 3055,
          "sha512": "fa4cc33caa5a3b5d876254a174b2e6b56d4c05713a621b378cfefbf6dd1f958bb885797ea80b01e778d6f2f084c779c8bd5eba826d23ef0b2cce91a932514f7b",
          "sha256": "de17a40f44d0f56c806d372dfc698fa13b83c3727b8408241a24a85d0a779d01",
          "sha1": "539848e85d76ca2471e6270e47b10164fadf839b",
          "md5": "34c0b8507fec1fde4092edc559d9ff5b"
        }
      ]
    }
  ]
}
